version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: vetappdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 55432:5432
    volumes:
      - vetappdb:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  vetappdb:
